services:
  _defaults:
    autowire: true
    autoconfigure: true

  PN\SeoBundle\Twig\:
    public: false
    resource: '../../Twig/*'

  PN\SeoBundle\Form\:
    public: false
    resource: '../../Form/*'

  PN\SeoBundle\Controller\:
    public: false
    resource: '../../Controller/*'
    tags: ['controller.service_arguments']

  PN\SeoBundle\Controller\Administration\:
    public: false
    resource: '../../Controller/Administration/*'
    tags: [ 'controller.service_arguments' ]

  PN\SeoBundle\Repository\:
    resource: '../../Repository/*'
    tags: [ 'doctrine.repository_service' ]

  PN\SeoBundle\Service\:
    public: true
    resource: '../../Service/*'

  pn.seo.listener.redirect:
    class: PN\SeoBundle\Listener\RedirectListener
    tags:
      - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }

  fe_seo:
    public: true
    class: PN\SeoBundle\Service\SeoService