<?php

namespace PN\SeoBundle\Repository;

use Doctrine\Bundle\DoctrineBundle\Repository\ServiceEntityRepository;
use Doctrine\Persistence\ManagerRegistry;
use PN\SeoBundle\Entity\Redirect404;
use PN\ServiceBundle\Utils\SQL;
use PN\ServiceBundle\Utils\Validate;

/**
 * Redirect404Repository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Redirect404Repository extends ServiceEntityRepository
{
    public function __construct(ManagerRegistry $registry)
    {
        parent::__construct($registry, Redirect404::class);
    }

    public function filter($search, $count = false, $startLimit = null, $endLimit = null)
    {

        $sortSQL = [
            0 => 'r.from',
            1 => 'r.to',
            2 => 'r.created',
        ];
        $connection = $this->getEntityManager()->getConnection();
        $where = false;
        $clause = '';

        $searchFiltered = new \stdClass();
        foreach ($search as $key => $value) {
            if (Validate::not_null($value) and !is_array($value)) {
                $searchFiltered->{$key} = substr($connection->quote($value), 1, -1);
            } else {
                $searchFiltered->{$key} = $value;
            }
        }


        if (isset($searchFiltered->string) and $searchFiltered->string) {

            if (SQL::validateSS($searchFiltered->string)) {
                $where = ($where) ? ' AND ( ' : ' WHERE ( ';
                $clause .= SQL::searchSCG($searchFiltered->string, 'r.id', $where);
                $clause .= SQL::searchSCG($searchFiltered->string, 'r.from', ' OR ');
                $clause .= SQL::searchSCG($searchFiltered->string, 'r.to', ' OR ');

                $clause .= " ) ";
            }
        }

        if ($count) {
            $sqlInner = "SELECT count(r.id) as `count` FROM redirect_404 r ";

            $statement = $connection->prepare($sqlInner);

            return $queryResult = $statement->executeQuery()->fetchOne();
        }

        $sql = "SELECT r.id FROM redirect_404 r";
        $sql .= $clause;

        if (isset($searchFiltered->ordr) and Validate::not_null($searchFiltered->ordr)) {
            $dir = $searchFiltered->ordr['dir'];
            $columnNumber = $searchFiltered->ordr['column'];
            if (isset($columnNumber) and array_key_exists($columnNumber, $sortSQL)) {
                $sql .= " ORDER BY ".$sortSQL[$columnNumber]." $dir";
            }
        } else {
            $sql .= ' ORDER BY r.id DESC';
        }

        if ($startLimit !== null and $endLimit !== null) {
            $sql .= " LIMIT ".$startLimit.", ".$endLimit;
        }

        $statement = $connection->prepare($sql);
        $filterResult = $statement->executeQuery()->fetchAllAssociative();
        $result = $ids = [];

        foreach ($filterResult as $key => $r) {
            $ids[] = $r['id'];
        }

        if (count($ids) > 0) {
            return $this->findBy(["id" => $ids]);
        }

        return $result;
    }

}
